### ISSUE TITLE
Running the docker command returns error

### ISSUE THREAD

**Issue by oninross** [google/emoji-scavenger-hunt#29]
After cloning the project locally and running the docker command returns the following error.  Please help

```
Step 1/8 : FROM gcr.io/tensorflow/tensorflow
manifest for gcr.io/tensorflow/tensorflow:latest not found
```

**Comment by tushuhei** [comment]
I pushed the fix to `update-tf-image-path` branch. Could you check if this fix resolves the issue?

**Comment by oninross** [comment]
Works like a charm mate! Custom training has already begun!  Cheers mate!  

~spoke too soon.  Last night it was working on a Mac machine.  Im on a Windows machine now and received the following error~

~Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)~

~and I tried reinstalling docker and got the following error now~

~Get https://registry-1.docker.io/v2/tensorflow/tensorflow/manifests/latest: unauthorized: incorrect username or password~

I thought it wasnt working.  It did get those errors at one point in time.  Then I logged off from Docker.  everything seems to be running as it should be

**Comment by oninross** [comment]
By the way, is this normal?  Before the issue above happened, I would be getting a Cross entropy of 0.000X or lower at Step 4000 and above.  Now its higher

![image](https://user-images.githubusercontent.com/2233813/41825365-44f82498-7862-11e8-87b5-0f439f56de9b.png)

**Comment by tushuhei** [comment]
Probably it's because the version of TensorFlow is changed from the last time you run the training.
Not sure which version you were using, but you can try changing line 1 of Dockerfile `FROM tensorflow/tensorflow` from to `FROM tensorflow/tensorflow:1.7.1` in order to specify the version you use, for example. Other versions (tags) are listed in https://hub.docker.com/r/tensorflow/tensorflow/tags/ If you don't specify any tag, `latest` should be used as default.

**Comment by oninross** [comment]
Im assuming that the later the version should be the better one right?

**Comment by Claytonhaddock** [comment]
Can you merge this PR?
